---
# Homepage configuration
# See https://fontawesome.com/search for icons options

title: "Dashboard"
subtitle: "Corgi Studios"
logo: "favicon.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Copyright Corgi Studios. All Rights Reserved</p>' # set false if you want to hide it.

# Optional theme customization
theme: default

# Optional theme customization (color overrrides)
# overrrides can also be done using CSS vars 
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Welcome to Corgi Studios!"
  # icon: "fa fa-grin"
  content: "Access company resources below."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Outlook"
    # icon: "fab fa-github"
    url: "https://outlook.office.com/mail"
    target: "_blank" # optional html a tag target attribute
  - name: "Member Access"
    # icon: "fas fa-book"
    url: "https://members.corgistudios.tech"
  - name: "CRM"
    url: "https://crm.corgistudios.tech"
  - name: "Live Panel"
    url: "https://live.corgistudios.tech/admin"
  - name: "Sign Out"
    url: "https://my.corgistudios.tech/cdn-cgi/access/logout"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).


services:
  -name: "Services"
  items:
    - name: "Member Access"
      url: "https://members.corgistudios.tech"
    - name: "TV"
      url: "https://live.corgistudios.tech"
    - name: "News"
      url: "https://news.corgistudios.tech"
    - name: "Creator Spreadsheet"
      url: "https://creators.corgistudios.tech"
    - name: "Profile"
      url: "https://profile.corgistudios.tech/"
  -name: "ADMIN ACCESS"
  items:
    - name: "Member"
      url: "https://members.corgistudios.tech/admin"
    - name: "TV"
      url: "https://live.corgistudios.tech/admin"
    - name: "News"
      url: "https://corgi-studios-news-admin.sanity.studio/structure"
    - name: "CRM Database"
      url: "https://crm.corgistudios.tech/" 
  -name: "Documentation"
  icon: "fas fa-cloud"
  items:
    - name: "Get started"
      icon: "fa-solid fa-download"
      subtitle: "Start using Homer in a few minutes"
      tag: "setup"
      url: "https://github.com/bastienwirtz/homer?tab=readme-ov-file#get-started"
    - name: "Configuration"
      icon: "fa-solid fa-sliders"
      subtitle: "Configuration options documentation"
      tag: "setup"
      url: "https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md"
    - name: "Theming"
      icon: "fa-solid fa-palette"
      subtitle: "Customize Homer appearance"
      tag: "theming"
      url: "https://github.com/bastienwirtz/homer/blob/main/docs/theming.md"
    - name: "Smart cards"
      icon: "fa-solid fa-palette"
      subtitle: "Displays dynamic information or actions."
      tag: "setup"
      url: "https://github.com/bastienwirtz/homer/blob/main/docs/customservices.md"
    - name: "Dashboard icons"
      icon: "fa-solid fa-icons"
      subtitle: "Dashboard icons"
      tag: "setup"
      url: "https://github.com/walkxcode/dashboard-icons"
